name: 80 Deploy Stage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/1-build.yml
  # Deploy Job
  deploy-stage:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      # Overwrite existing environment-config
      - name: Prepare environment config
        run: |
          echo '${{ vars.SMTALENT_REACT_ENVIRONMENT_CONFIG }}' > ./dist/environment-config.js
      # Deploy to stage environment
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN_SMARTALENT_CD }}
          publish_dir: ./dist
